# Generated by Django 5.0.6 on 2024-05-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed'), ('Open', 'Open')], default='Open', max_length=7, verbose_name='Status'),
        ),
    ]
